version: '3.8'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DB=todos

  db:
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=todos

volumes:
  db-data: